refactoring, role doesn't have separate 'set_' variables, expanding tests

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,17 +31,24 @@ script:
   # Syntax check
   - sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --syntax-check
 
-  # Playbook run test
-  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local"
+  # Running role with vars undefined should pass but make no changes
+  - >
+    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local
+    | grep -q 'changed=0.*failed=0'
+    && (echo 'Undefined vars test: pass' && exit 0)
+    || (echo 'Undefined vars test: fail' && exit 1)
+
+  # Set options
+  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e sudoers_mailto=test@example.com sudoers_mail_always=true"
 
   # Idempotence test
   - >
-    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local
+    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e sudoers_mailto=test@example.com sudoers_mail_always=true
     | grep -q 'changed=0.*failed=0'
     && (echo 'Idempotence test: pass' && exit 0)
     || (echo 'Idempotence test: fail' && exit 1)
 
-  # Test that configuration options actually applied
+  # Test that configuration options were set
   - >
     sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=test@example.com"
     && (echo 'mailto test: pass' && exit 0)
@@ -51,6 +58,30 @@ script:
     sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always"
     && (echo 'mail_always test: pass' && exit 0)
     || (echo 'mail_always test: fail' && exit 1)
+
+  # Unset options
+  - "sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e sudoers_mailto=false sudoers_mail_always=false"
+
+  # Idempotence test
+  - >
+    sudo docker exec test_dummy ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml -i tests/inventory --connection=local -e sudoers_mailto=false sudoers_mail_always=false
+    | grep -q 'changed=0.*failed=0'
+    && (echo 'Idempotence test: pass' && exit 0)
+    || (echo 'Idempotence test: fail' && exit 1)
+
+  # Test that configuration options were unset
+  - >
+    if sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=test@example.com"
+    then echo 'mailto absent test: fail' && exit 1
+    else echo 'mailto absent test: pass' && exit 0
+    fi
+
+  - >
+    if sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always"
+    then echo 'mail_always absent test: fail' && exit 1
+    else echo 'mail_always absent test: pass' && exit 0
+    fi
+
 
 notifications:
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
