parens in conditionals

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -71,15 +71,15 @@ script:
 
   # Test that configuration options were unset
   - >
-    if sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=test@example.com"
-    then echo 'mailto absent test: fail' && exit 1
-    else echo 'mailto absent test: pass' && exit 0
+    if (sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mailto=test@example.com")
+    then (echo 'mailto absent test: fail' && exit 1)
+    else (echo 'mailto absent test: pass' && exit 0)
     fi
 
   - >
-    if sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always"
-    then echo 'mail_always absent test: fail' && exit 1
-    else echo 'mail_always absent test: pass' && exit 0
+    if (sudo docker exec test_dummy cat /etc/sudoers | grep -q "Defaults.*mail_always")
+    then (echo 'mail_always absent test: fail' && exit 1)
+    else (echo 'mail_always absent test: pass' && exit 0)
     fi
 
 
